spring:
  datasource:
#    외부 접속
    url: jdbc:mariadb://hanta.gg:12402/ego-api-server
#    집 접속
#    url: jdbc:mariadb://192.168.219.101:3306/ego-api-server-dev
#    빌드 후 배포
#    url: jdbc:mariadb://localhost:3306/ego-api-server
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: hanta950502@
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
